version: '3.8'

services:
  api-mock-contract:
    build: .
    container_name: api-mock-contract-mvp
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "const http = require('http'); const options = { host: 'localhost', port: 3000, path: '/api/health', timeout: 2000 }; const request = http.request(options, (res) => { process.exit(0); }); request.on('error', () => { process.exit(1); }); request.end();"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - api-network

networks:
  api-network:
    driver: bridge